---
driver:
  name: ec2
  aws_ssh_key_id: test
#  availability_zone: a
#  subnet_id: subnet-eacb348f
  instance_type: t2.micro
#  image_id: ami-c3b3b1f3
  security_group_ids: ['sg-06ce7561']
#  retryable_tries: 120

provisioner:
  name: chef_zero

transport:
  username: ec2-user
  ssh_key: /home/ec2-user/aws-test.pem

platforms:
  - name: chef_base
    driver:
      image_id: ami-63b25203
#      username: ec2-user
      region: us-west-2

suites:
  - name: default
    data_bags_path: "../../data_bags"
    run_list: ["recipe[mercury::default]"]
    provisioner:
      encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
    attributes:
      mercury:
        secret_file: '/tmp/kitchen/encrypted_data_bag_secret'
